# Generated by Django 6.1.1 on 2026-09-11 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('booking_code', models.CharField(editable=False, max_length=12, unique=True, verbose_name='Code de réservation')),
                ('check_in', models.DateField(db_index=True, verbose_name='Arrivée')),
                ('check_out', models.DateField(verbose_name='Départ')),
                ('adults', models.PositiveSmallIntegerField(default=2, verbose_name='Adultes')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='Enfants')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par nuit (figé)')),
                ('nights', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Nombre de nuits')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxes')),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de service')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Prix total')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Annulée le')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotels.hotel', verbose_name='Hôtel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotels.room', verbose_name='Chambre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='bookings_bo_user_id_5943d6_idx'), models.Index(fields=['hotel'], name='bookings_bo_hotel_i_c0ccbf_idx'), models.Index(fields=['room', 'check_in'], name='bookings_bo_room_id_95cead_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='booking_check_out_after_check_in'), models.CheckConstraint(condition=models.Q(('adults__gte', 1)), name='booking_at_least_one_adult')],
            },
        ),
    ]
