# Generated by Django 6.1.1 on 2026-09-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_exclusion_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Rappel d'arrivée envoyé le"),
        ),
    ]
