# Generated by Django 6.1.1 on 2026-09-11 19:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Ville')),
                ('country', models.CharField(db_index=True, max_length=100, verbose_name='Pays')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='Longitude')),
                ('stars', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Étoiles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='Note moyenne')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'avis")),
                ('amenities', models.ManyToManyField(blank=True, related_name='hotels', to='hotels.amenity', verbose_name='Équipements')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'hotel_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hotels', to=settings.AUTH_USER_MODEL, verbose_name='Gestionnaire')),
            ],
            options={
                'verbose_name': 'Hôtel',
                'verbose_name_plural': 'Hôtels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='hotels.hotel', verbose_name='Hôtel')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('image', models.ImageField(upload_to='hotels/%Y/%m/', verbose_name='Image')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Texte alternatif')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Image principale')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel', verbose_name='Hôtel')),
            ],
            options={
                'verbose_name': "Image d'hôtel",
                'verbose_name_plural': "Images d'hôtels",
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('room_number', models.CharField(max_length=20, verbose_name='Numéro de chambre')),
                ('room_type', models.CharField(choices=[('single', 'Simple'), ('double', 'Double'), ('suite', 'Suite'), ('family', 'Familiale')], default='double', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_per_night', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix par nuit')),
                ('max_occupancy', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité maximale')),
                ('beds', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de lits')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('amenities', models.ManyToManyField(blank=True, related_name='rooms', to='hotels.amenity', verbose_name='Équipements')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel', verbose_name='Hôtel')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['hotel', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('image', models.ImageField(upload_to='rooms/%Y/%m/', verbose_name='Image')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Texte alternatif')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Image principale')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.room', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Image de chambre',
                'verbose_name_plural': 'Images de chambres',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['city', 'is_active'], name='hotels_hote_city_a8c2d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 5)), name='hotel_stars_range'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='hotel_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='hotel_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'hotel'), name='unique_user_hotel_favorite'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'is_active'], name='hotels_room_hotel_i_8edaf3_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['price_per_night'], name='hotels_room_price_p_ddffaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hotel', 'room_number'), name='unique_room_number_per_hotel'),
        ),
    ]
