# Generated by Django 6.1.1 on 2026-09-11 19:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant')),
                ('currency', models.CharField(default='eur', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('partially_refunded', 'Partiellement remboursé')], db_index=True, default='pending', max_length=25, verbose_name='Statut')),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, verbose_name='Session Stripe Checkout')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, verbose_name='PaymentIntent Stripe')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Moyen de paiement')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='bookings.booking', verbose_name='Réservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='payments_pa_user_id_5bbfc5_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx')],
            },
        ),
    ]
